[workspace]
members = [
    # "zomes/group",
    # "zomes/request",
    "zomes/profiles",
    "zomes/contacts",
    "zomes/aggregator",
    "zomes/preference/integrity",
    "zomes/preference/coordinator",
    "zomes/p2pmessage",
    # "zomes/joining_code",
    "commons/file_types", 
    "zomes/group/integrity",
    "zomes/group/coordinator",
    "zomes/group/types/integrity_types",
    "zomes/group/types/coordinator_types",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
