[workspace]
members = [
    "zomes/group",
    "zomes/profiles/integrity",
    "zomes/profiles/coordinator",
    "zomes/profiles/types",
    "zomes/contacts",
    "zomes/aggregator",
    "zomes/preference/integrity",
    "zomes/preference/coordinator",
    "zomes/p2pmessage",
    "commons/file_types", 
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
